name: ${name}
main: com.nyancraft.reportrts.ReportRTS
version: ${version}
author: ProjectInfinity
commands:
  ticket:
    description: General user commands for ReportRTS
    usage: /<command> [action] [arguments]
  reportrts:
    description: General management commands for ReportRTS
    aliases: [rts]
    usage: /<command> [reload | ban | unban | reset | stats <player> | help | notifications | duty | find <completed|created>]
permissions:
  reportrts.user:
    description: Give this to all of your regular players.
    default: true
    children:
      reportrts.command.open: true
      reportrts.command.read.self: true
      reportrts.command.close.self: true
  reportrts.mod:
    description: Backwards compatibility for reportrts.staff, will be removed in the future.
    default: op
    children:
      reportrts.staff: true
  reportrts.staff:
    description: Give this to all staff members.
    default: op
  reportrts.bypass.claim:
    description: Permission to bypass the claim of other staff members.
    default: op
  reportrts.bypass.limit:
    description: Permission to bypass the limits in this plugin.
    default: op
  reportrts.command.open:
    description: Permission to open a ticket.
    default: op
  reportrts.command.open.unlimited:
    description: Permission to open an unlimited amounts of tickets.
    default: op
  reportrts.command.read:
    description: Permission to read all tickets.
    default: op
  reportrts.command.read.self:
    description: Permission to read your own tickets.
    default: op
  reportrts.command.read.self.closed:
    description: Permission to read your own closed tickets.
    default: op
  reportrts.command.comment:
    description: Permission to comment on a ticket.
    default: op
  reportrts.command.close:
    description: Permission to close tickets.
    default: op
  reportrts.command.close.self:
    description: Permission to close your own tickets.
    default: op
  reportrts.command.reopen:
    description: Permission to reopen tickets.
    default: op
  reportrts.command.teleport:
    description: Permission to teleport to tickets.
    default: op
  reportrts.command.reload:
    description: Permission to reload configuration.
    default: op
  reportrts.command.reset:
    description: Permission to reset the plugin.
    default: op
  reportrts.command.stats:
    description: Permission to look up staff stats.
    default: op
  reportrts.command.ban:
    description: Permission to ban people from ReportRTS.
    default: op
  reportrts.command.hold:
    description: Permission to put tickets on hold.
    default: op
  reportrts.command.claim:
    description: Permission to claim and unclaim tickets.
    default: op
  reportrts.command.list:
    description: Permission to list online staff.
    default: op
  reportrts.command.broadcast:
    description: Permission to broadcast to staff.
    default: op
  reportrts.command.help:
    description: Permission to see the help page.
    default: op
  reportrts.command.notifications:
    description: Permission to manage notifications.
    default: op
  reportrts.command.assign:
    description: Permission to assign tickets.
    default: op